# Generated by Django 4.2.7 on 2023-11-18 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0002_communitycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitycomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
