# Generated by Django 4.2.7 on 2023-11-11 22:00

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='channel_art',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='channel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel', to=settings.AUTH_USER_MODEL),
        ),
    ]
