# Generated by Django 4.2.7 on 2023-11-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_channel_channel_art_alter_channel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='business_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='instagram',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='make_business_email_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='make_business_location_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channel',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='channel',
            name='twitter',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
