# Generated by Django 4.2.7 on 2023-11-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_alter_community_options_alter_community_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
